# Generated by Django 4.1.7 on 2024-01-20 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('History_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Doc_ID', models.CharField(max_length=100)),
                ('Date_Time', models.DateTimeField()),
                ('Comment', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckList_Trans_Header',
            fields=[
                ('Doc_ID', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_Start_Date', models.DateTimeField(auto_now_add=True)),
                ('inspection_End_Date', models.DateTimeField(blank=True, null=True)),
                ('Contractor', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Chainage', models.CharField(max_length=100)),
                ('Well_implimented_Quality_Checks', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Fairly_implimented_Quality_Checks', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Poorly_implimented_Quality_Checks', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Quality_Engineer_Comment', models.CharField(blank=True, max_length=220)),
                ('Project_Head_Status', models.CharField(choices=[('Noted, for necessary action..!', 'Noted, for necessary action..!')], default='Unspecified', max_length=70)),
                ('assigned_to', models.JSONField(default=list)),
                ('assigned_to_ProjectQA', models.JSONField(default=list)),
                ('assigned_to_ProjectHead', models.JSONField(default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('checklist_status', models.CharField(choices=[('Completed_By_SiteEngineer & Active_At_DHEQA', 'Completed_By_SiteEngineer & Active_At_DHEQA'), ('PQA and ProjectHead Queue', 'PQA and ProjectHead Queue'), ('Completed_By_DHEQA & Active_At_ProjectQA', 'Completed_By_DHEQA & Active_At_ProjectQA'), ('Completed_By_DHEQA & Active_At_ProjectHead', 'Completed_By_DHEQA & Active_At_ProjectHead'), ('Completed_By_ProjectQA & Active_At_ProjectHead', 'Completed_By_ProjectQA & Active_At_ProjectHead'), ('Completed_By_ProjectHead', 'Completed_By_ProjectHead'), ('Rejected', 'Rejected')], max_length=70)),
                ('rejected_byDHEQA', models.BooleanField(default=False)),
                ('rejection_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('CheckList_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.checklist_header')),
                ('Name_Of_ABLStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('Project_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.projects')),
                ('Site_Name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='administration.sites')),
                ('Structural_Element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.structural_element')),
            ],
        ),
        migrations.CreateModel(
            name='CheckList_Trans_Details',
            fields=[
                ('CheckList_Trans_Details_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CheckList_Item_ID', models.CharField(max_length=500)),
                ('Site_Engineer_Status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Na', 'NA'), ('Partial', 'Partial'), ('Not_Observed', 'Not Observed')], default='Unspecified', max_length=70)),
                ('Site_DH_EQA_Status', models.CharField(choices=[('Yes', ' Yes'), ('No', ' No'), ('NA', ' NA'), ('Partial', ' Partial')], default='Unspecified', max_length=70)),
                ('Site_Engineer_Comment', models.CharField(blank=True, max_length=220)),
                ('Site_DH_EQA_Comment', models.CharField(blank=True, max_length=220)),
                ('CheckList_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_id_details', to='checklists.checklist_trans_header')),
                ('Doc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_id_details', to='checklists.checklist_trans_header')),
            ],
        ),
    ]
